### ISSUE TITLE
Error when building OSX UE5.1

### ISSUE THREAD

**Issue by todernst** [monsieurgustav/UE-OSC#91]
Hi, I've been using this great plugin since 4.6 and am having the first compilation issues on OSX for UE5.1

Building 3 actions with 3 processes...
[1/3] Compile Module.UE_OSC.cpp
In file included from /Users/[username]/Documents/Unreal Projects/MyProject/Plugins/UE-OSC/Intermediate/Build/Mac/x86_64/UnrealEditor/Development/UE_OSC/Module.UE_OSC.cpp:10:
In file included from /Users/[username]/Documents/Unreal Projects/MyProject/Plugins/UE-OSC/Source/UE_OSC/Private/Common/OscFunctionLibrary.cpp:2:
/Users/[username]/Documents/Unreal Projects/MyProject/Plugins/UE-OSC/Source/UE_OSC/Private/Common/OscUtils.h:2:10: fatal error: 'UObject\NameTypes.h' file not found
#include <UObject\NameTypes.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
[2/3] Link UnrealEditor-UE_OSC.dylib cancelled
[3/3] WriteMetadata MyProjectEditor.target cancelled
Command ExternalBuildToolExecution failed with a nonzero exit code

**Comment by monsieurgustav** [comment]
Oh sorry, I left a backslash in the file path...
It's fixed!
